# Generated by Django 4.1.3 on 2022-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('alim_id', models.AutoField(primary_key=True, serialize=False)),
                ('alim_nombre', models.CharField(max_length=80, unique=True)),
                ('alim_precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alim_categoria', models.CharField(blank=True, max_length=12, null=True)),
                ('alim_comida_categoria', models.CharField(blank=True, max_length=10, null=True)),
                ('alim_extras_categoria', models.CharField(blank=True, max_length=7, null=True)),
                ('alim_bebida_categoria', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'alimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_num_alimentos', models.IntegerField()),
                ('ord_fecha', models.DateField(blank=True, null=True)),
                ('ord_estatus', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenAlimento',
            fields=[
                ('ord_alim_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'orden_alimento',
                'managed': False,
            },
        ),
    ]
